/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SERVICIOPDVSA_H_RPCGEN
#define _SERVICIOPDVSA_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define SERVICIOPDVSA 0x20000001
#define SERVICIOPDVSAVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define PEDIR_GASOLINA 1
extern  char ** pedir_gasolina_1(char **, CLIENT *);
extern  char ** pedir_gasolina_1_svc(char **, struct svc_req *);
#define PEDIR_TIEMPO 2
extern  int * pedir_tiempo_1(void *, CLIENT *);
extern  int * pedir_tiempo_1_svc(void *, struct svc_req *);
extern int serviciopdvsa_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define PEDIR_GASOLINA 1
extern  char ** pedir_gasolina_1();
extern  char ** pedir_gasolina_1_svc();
#define PEDIR_TIEMPO 2
extern  int * pedir_tiempo_1();
extern  int * pedir_tiempo_1_svc();
extern int serviciopdvsa_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_SERVICIOPDVSA_H_RPCGEN */
